opencv: build issue
opencv failes to build do to a restricted license.

ERROR: Nothing PROVIDES 'libav' (but /home/akuster/oss/clean/meta-openembedded/meta-oe/recipes-support/opencv/opencv_2.4.bb DEPENDS on or otherwise requires it)
ERROR: libav was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
ERROR: Required build target 'opencv-samples' has no buildable providers.
Missing or unbuildable dependency chain was: ['opencv-samples', 'opencv', 'libav']

blacklist both opencv and opencv-samples until the libav license issue is resolved.

Signed-off-by: Armin Kuster <akuster808@gmail.com>