fingerterm: update SRC_URI
the previous source hqh.unlink.org/harmattan is dead. Update to using
repo on github.

This fixes build error:
WARNING: Failed to fetch URL http://hqh.unlink.org/harmattan/fingerterm-1.0.2.tar.gz, attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command failed with exit code 4, no output
ERROR: Function failed: Fetcher failure for URL: 'http://hqh.unlink.org/harmattan/fingerterm-1.0.2.tar.gz'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/akuster/oss/clean/poky/build/tmp/work/ppc7400-poky-linux/fingerterm/1.0.2-r0/temp/log.do_fetch.11225
ERROR: Task 6183 (/home/akuster/oss/clean/meta-openembedded/meta-oe/recipes-qt/fingerterm/fingerterm_1.0.2.bb, do_fetch) failed with exit code '1'

Signed-off-by: Armin Kuster <akuster808@gmail.com>