ckermit: update SRC_URI
it seems ftp does not work. changing to http.

WARNING: Failed to fetch URL ftp://ftp.kermitproject.org/kermit/archives/cku302.tar.gz;subdir=ckermit-302, attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command failed with exit code 4, no output
ERROR: Function failed: Fetcher failure for URL: 'ftp://ftp.kermitproject.org/kermit/archives/cku302.tar.gz;subdir=ckermit-302'. Unable to fetch URL from any source.

Signed-off-by: Armin Kuster <akuster808@gmail.com>